export PROJECTS_ROOT='/Volumes/warehouse/projects'
export CONDA_HOME="${PROJECTS_ROOT}/miniconda"


## PATH additions
export PATH="$PATH:${PROJECTS_ROOT}/Applications/ASP/bin"


## Common includes
source ${PROJECTS_ROOT}/environment-setups/common/imports
# Third party
source /usr/local/etc/bash_completion.d/git-completion.bash


## Terminal prompt
PS1="$GREEN\W:$GREEN$RED\$(parse_git_branch)$NO_COLOUR\$ "


## BASH settings
# No dups in bash_history
export HISTCONTROL=ignoreboth:erasedups
export CLICOLOR=1


## Aliases
alias ll='ls -al'
alias snow_rs='conda activate snow_rs'
alias snow_aso='export GDAL_CACHEMAX=20%; conda activate snow_aso'
alias dem_tools='conda activate dem_tools'

