export PROJECTS_ROOT='/Volumes/warehouse/projects'
export CONDA_HOME="${PROJECTS_ROOT}/miniconda"


## Common includes
source ${PROJECTS_ROOT}/environment-setups/common/imports.bash
# Third party
source /usr/local/etc/bash_completion.d/git-completion.bash


## Terminal prompt
PS1="\u:($BLACK\W$NO_COLOUR)$RED\$(parse_git_branch)$NO_COLOUR\$ "


## BASH settings
# No dups in bash_history
export HISTCONTROL=ignoreboth:erasedups:rm:ll:ls:git
export CLICOLOR=1


## Aliases
alias ll='ls -al'

