export PROJECTS_ROOT="${HOME}/projects"
export CONDA_HOME="${HOME}/miniconda3"


# PATH additions
PATH=${HOME}/bin:${PROJECTS_ROOT}/bin:${HOME}/ASP/current/bin:${PATH}


## Common includes
source ${PROJECTS_ROOT}/environment-setups/common/imports
# GIT customization
source ${HOME}/miniconda3/share/bash-completion/completions/git


## Terminal prompt
PS1="$BLUE[\h]$BLUE $YELLOW\W:$YELLOW$RED\$(parse_git_branch)$NO_COLOUR\$ "


## BASH settings
LS_COLORS=$LS_COLORS:'di=34:ln=4;95:ex=32:or=31' ; export LS_COLORS


## Aliases
alias ll='ls -al --color=always'
alias dem_tools='conda activate dem_tools'

